#!/usr/bin/env python3
"""Generates the clicker sound asset.

Original, synthesized, and deterministic (fixed seed) so the committed WAV can be regenerated byte-for-byte.
Targets DESIGN_SYSTEM.md's brief: mechanical, dry, no reverb, 30-70ms (see soundDurationBudgetMs in @pawcue/ui).

Usage: python3 scripts/generate-click.py
"""
import wave, struct, math, random, pathlib

SR = 44100
DUR = 0.045
OUT = pathlib.Path(__file__).parent.parent / "assets" / "audio" / "click.wav"

n = int(SR * DUR)
random.seed(7)

samples = []
for i in range(n):
    t = i / SR
    env = math.exp(-t * 260.0)
    click = random.uniform(-1.0, 1.0) * 0.55
    body = math.sin(2 * math.pi * 2100 * t) * 0.30 + math.sin(2 * math.pi * 3400 * t) * 0.18
    attack = min(1.0, t / 0.0006)
    samples.append(max(-1.0, min(1.0, (click + body) * env * attack)))

fade = int(SR * 0.003)
for i in range(fade):
    samples[n - fade + i] *= (fade - i) / fade

OUT.parent.mkdir(parents=True, exist_ok=True)
with wave.open(str(OUT), "w") as w:
    w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
    w.writeframes(b"".join(struct.pack("<h", int(s * 32767)) for s in samples))
print(f"wrote {OUT} ({DUR*1000:.0f}ms)")
