import { readFileSync } from "node:fs";
import { join } from "node:path";
import { CLICK_SOUNDS } from "../src/audio/click-sounds";

/**
 * Specification tests for the clicker audio assets.
 *
 * The sounds are generated by `tools/audio/generate-click-sounds.mjs`, so these assertions are what stops a
 * regeneration from silently shipping something that no longer meets the brief — a leading gap, a ringing tail,
 * a clipped peak, or one candidate louder than the others in a listening test that is supposed to compare them
 * fairly. Every threshold below is a stated requirement, not a snapshot of current output.
 */

const AUDIO_DIR = join(__dirname, "..", "assets", "audio");

const FILES = [
  "click-classic.wav",
  "click-soft.wav",
  "click-crisp.wav",
] as const;

interface DecodedWav {
  sampleRate: number;
  channels: number;
  bitsPerSample: number;
  samples: Float64Array;
  durationMs: number;
}

function decodeWav(fileName: string): DecodedWav {
  const buffer = readFileSync(join(AUDIO_DIR, fileName));

  expect(buffer.toString("ascii", 0, 4)).toBe("RIFF");
  expect(buffer.toString("ascii", 8, 12)).toBe("WAVE");
  expect(buffer.readUInt16LE(20)).toBe(1); // uncompressed PCM

  const channels = buffer.readUInt16LE(22);
  const sampleRate = buffer.readUInt32LE(24);
  const bitsPerSample = buffer.readUInt16LE(34);
  const dataBytes = buffer.readUInt32LE(40);

  const count = dataBytes / 2;
  const samples = new Float64Array(count);
  for (let i = 0; i < count; i += 1) {
    samples[i] = buffer.readInt16LE(44 + i * 2) / 32767;
  }

  return {
    sampleRate,
    channels,
    bitsPerSample,
    samples,
    durationMs: (count / sampleRate) * 1000,
  };
}

function peakBetween(samples: Float64Array, from: number, to: number): number {
  let max = 0;
  for (let i = Math.max(0, from); i < Math.min(samples.length, to); i += 1) {
    max = Math.max(max, Math.abs(samples[i] ?? 0));
  }
  return max;
}

function rms(samples: Float64Array): number {
  let sum = 0;
  for (const sample of samples) sum += sample * sample;
  return Math.sqrt(sum / samples.length);
}

describe.each(FILES)("%s", (fileName) => {
  const wav = decodeWav(fileName);
  const peak = peakBetween(wav.samples, 0, wav.samples.length);

  it("is mono 16-bit PCM at 48kHz", () => {
    expect(wav.channels).toBe(1);
    expect(wav.bitsPerSample).toBe(16);
    // 48kHz is the native rate of the Android audio path and current iOS hardware, so nothing has to resample a
    // 40ms transient — resampling is exactly where a crisp attack gets smeared.
    expect(wav.sampleRate).toBe(48_000);
  });

  it("lasts 35–70ms", () => {
    expect(wav.durationMs).toBeGreaterThanOrEqual(35);
    expect(wav.durationMs).toBeLessThanOrEqual(70);
  });

  it("has no leading silence", () => {
    // The transient must begin at the very start of the file. Anything else is latency baked into the asset that
    // no amount of playback engineering can recover.
    const firstMillisecond = peakBetween(wav.samples, 0, wav.sampleRate / 1000);
    expect(firstMillisecond / peak).toBeGreaterThan(0.5);
  });

  it("reaches full level almost immediately", () => {
    const firstFiveMs = peakBetween(
      wav.samples,
      0,
      (wav.sampleRate * 5) / 1000,
    );
    expect(firstFiveMs).toBeCloseTo(peak, 5);
  });

  it("does not clip", () => {
    expect(peak).toBeLessThan(0.95);
    const atRail = Array.from(wav.samples).filter((s) => Math.abs(s) >= 0.999);
    expect(atRail).toHaveLength(0);
  });

  it("is loud enough to be clearly audible", () => {
    // Peak within 6dB of the ceiling. A transient this short is perceived by its peak, not its average.
    expect(peak).toBeGreaterThan(0.45);
  });

  it("has no ringing tail and ends in true silence", () => {
    const lastMillisecond = peakBetween(
      wav.samples,
      wav.samples.length - wav.sampleRate / 1000,
      wav.samples.length,
    );
    // Below -60dB relative to the peak: inaudible, so repeated presses cannot smear into one another.
    expect(lastMillisecond / peak).toBeLessThan(0.001);
    expect(wav.samples[wav.samples.length - 1]).toBe(0);
  });

  it("decays fast enough to stay dry", () => {
    // Everything above -26dB of the peak must be finished within 30ms — that is what "dry, no reverb" means
    // measurably, and it is what keeps rapid presses from overlapping into a rattle.
    let lastAudible = 0;
    for (let i = wav.samples.length - 1; i >= 0; i -= 1) {
      if (Math.abs(wav.samples[i] ?? 0) > 0.05 * peak) {
        lastAudible = (i / wav.sampleRate) * 1000;
        break;
      }
    }
    expect(lastAudible).toBeLessThan(30);
  });
});

describe("the candidate set", () => {
  const decoded = FILES.map(decodeWav);

  it("matches loudness across candidates so a listening test compares character, not volume", () => {
    const levels = decoded.map((wav) => 20 * Math.log10(rms(wav.samples)));
    const spread = Math.max(...levels) - Math.min(...levels);
    expect(spread).toBeLessThan(1.5);
  });

  it("gives each candidate a distinct brightness", () => {
    // Zero-crossing rate stands in for spectral centroid: cheap, and more than sharp enough to prove the three
    // are genuinely different sounds rather than three copies of one.
    const brightness = decoded.map((wav) => {
      let crossings = 0;
      for (let i = 1; i < wav.samples.length; i += 1) {
        if (
          Math.sign(wav.samples[i] ?? 0) !== Math.sign(wav.samples[i - 1] ?? 0)
        ) {
          crossings += 1;
        }
      }
      return crossings / (wav.durationMs / 1000);
    });

    const [classic = 0, soft = 0, crisp = 0] = brightness;

    // Ordered soft < classic < crisp, matching their stated characters: B is the warm one, C the cutting one.
    expect(classic).toBeGreaterThan(soft * 1.15);
    expect(crisp).toBeGreaterThan(classic * 1.15);
  });

  it("exposes exactly the three candidates the QA selector offers", () => {
    expect(CLICK_SOUNDS.map((sound) => sound.id)).toEqual([
      "classic",
      "soft",
      "crisp",
    ]);
  });
});
