/**
 * The breed list — a local, structured dataset for the breed picker and the avatar system.
 *
 * Presentation data only. The domain layer deliberately has no breed-traits lookup (see `models/dog.ts`), and
 * nothing here feeds training decisions: `group`, `size` and `ears` exist so a dog can *look* like itself in the
 * app, and so a user can find their breed in two keystrokes.
 *
 * The stored value stays the breed's English name (the `dogs.breed` column is free text and existing rows hold
 * whatever the owner typed), so a value that matches an entry here displays in the user's language and one that
 * does not still displays as typed. Hebrew names follow common Israeli usage rather than transliteration rules.
 *
 * `popular` puts the breeds most owners are looking for at the top before they type anything. Add to this list
 * freely; keep `id` stable, because avatar artwork will be keyed by it when real assets land.
 */

export type BreedGroup =
  | "sporting"
  | "herding"
  | "hound"
  | "working"
  | "terrier"
  | "toy"
  | "non_sporting"
  | "spitz"
  | "mixed";

export type BreedSize = "small" | "medium" | "large";

/** The one visual trait that most changes a dog's silhouette. */
export type EarShape = "floppy" | "pointed" | "folded";

export interface Breed {
  id: string;
  en: string;
  he: string;
  group: BreedGroup;
  size: BreedSize;
  ears: EarShape;
  popular?: boolean;
}

export const MIXED_BREED_ID = "mixed";

const b = (
  id: string,
  en: string,
  he: string,
  group: BreedGroup,
  size: BreedSize,
  ears: EarShape,
  popular = false,
): Breed => ({
  id,
  en,
  he,
  group,
  size,
  ears,
  ...(popular ? { popular } : {}),
});

export const BREEDS: readonly Breed[] = [
  b(
    MIXED_BREED_ID,
    "Mixed breed",
    "כלב מעורב",
    "mixed",
    "medium",
    "folded",
    true,
  ),
  b(
    "labrador_retriever",
    "Labrador Retriever",
    "לברדור רטריבר",
    "sporting",
    "large",
    "floppy",
    true,
  ),
  b(
    "golden_retriever",
    "Golden Retriever",
    "גולדן רטריבר",
    "sporting",
    "large",
    "floppy",
    true,
  ),
  b(
    "german_shepherd",
    "German Shepherd",
    "רועה גרמני",
    "herding",
    "large",
    "pointed",
    true,
  ),
  b(
    "belgian_malinois",
    "Belgian Malinois",
    "מלינואה בלגי",
    "herding",
    "large",
    "pointed",
    true,
  ),
  b(
    "canaan_dog",
    "Canaan Dog",
    "כלב כנעני",
    "herding",
    "medium",
    "pointed",
    true,
  ),
  b(
    "french_bulldog",
    "French Bulldog",
    "בולדוג צרפתי",
    "non_sporting",
    "small",
    "pointed",
    true,
  ),
  b("poodle", "Poodle", "פודל", "non_sporting", "medium", "floppy", true),
  b("toy_poodle", "Toy Poodle", "פודל טוי", "toy", "small", "floppy"),
  b(
    "miniature_poodle",
    "Miniature Poodle",
    "פודל מיניאטורי",
    "non_sporting",
    "small",
    "floppy",
  ),
  b(
    "english_bulldog",
    "Bulldog",
    "בולדוג אנגלי",
    "non_sporting",
    "medium",
    "folded",
  ),
  b("beagle", "Beagle", "ביגל", "hound", "medium", "floppy", true),
  b(
    "rottweiler",
    "Rottweiler",
    "רוטוויילר",
    "working",
    "large",
    "folded",
    true,
  ),
  b("dachshund", "Dachshund", "תחש", "hound", "small", "floppy", true),
  b(
    "yorkshire_terrier",
    "Yorkshire Terrier",
    "יורקשייר טרייר",
    "toy",
    "small",
    "pointed",
    true,
  ),
  b(
    "siberian_husky",
    "Siberian Husky",
    "האסקי סיבירי",
    "spitz",
    "large",
    "pointed",
    true,
  ),
  b(
    "cavalier_king_charles_spaniel",
    "Cavalier King Charles Spaniel",
    "קאבאלייר קינג צ'ארלס ספנייל",
    "toy",
    "small",
    "floppy",
    true,
  ),
  b(
    "pembroke_welsh_corgi",
    "Pembroke Welsh Corgi",
    "קורגי",
    "herding",
    "small",
    "pointed",
    true,
  ),
  b(
    "doberman_pinscher",
    "Doberman Pinscher",
    "דוברמן",
    "working",
    "large",
    "folded",
  ),
  b(
    "australian_shepherd",
    "Australian Shepherd",
    "רועה אוסטרלי",
    "herding",
    "medium",
    "folded",
    true,
  ),
  b(
    "miniature_schnauzer",
    "Miniature Schnauzer",
    "שנאוצר ננסי",
    "terrier",
    "small",
    "folded",
    true,
  ),
  b("boxer", "Boxer", "בוקסר", "working", "large", "folded", true),
  b("great_dane", "Great Dane", "דני ענק", "working", "large", "folded"),
  b("shih_tzu", "Shih Tzu", "שי צו", "toy", "small", "floppy", true),
  b("cane_corso", "Cane Corso", "קאנה קורסו", "working", "large", "folded"),
  b(
    "boston_terrier",
    "Boston Terrier",
    "בוסטון טרייר",
    "non_sporting",
    "small",
    "pointed",
  ),
  b("pomeranian", "Pomeranian", "פומרניאן", "toy", "small", "pointed", true),
  b("havanese", "Havanese", "הוואנז", "toy", "small", "floppy"),
  b(
    "shetland_sheepdog",
    "Shetland Sheepdog",
    "שלטי",
    "herding",
    "small",
    "pointed",
  ),
  b(
    "bernese_mountain_dog",
    "Bernese Mountain Dog",
    "ברנר",
    "working",
    "large",
    "floppy",
  ),
  b("brittany", "Brittany", "בריטני ספנייל", "sporting", "medium", "floppy"),
  b(
    "english_springer_spaniel",
    "English Springer Spaniel",
    "ספרינגר ספנייל",
    "sporting",
    "medium",
    "floppy",
  ),
  b(
    "cocker_spaniel",
    "Cocker Spaniel",
    "קוקר ספנייל",
    "sporting",
    "small",
    "floppy",
    true,
  ),
  b(
    "border_collie",
    "Border Collie",
    "בורדר קולי",
    "herding",
    "medium",
    "folded",
    true,
  ),
  b("vizsla", "Vizsla", "ויזלה", "sporting", "large", "floppy"),
  b("pug", "Pug", "פאג", "toy", "small", "folded", true),
  b("mastiff", "Mastiff", "מסטיף", "working", "large", "floppy"),
  b("chihuahua", "Chihuahua", "צ'יוואווה", "toy", "small", "pointed", true),
  b("maltese", "Maltese", "מלטזי", "toy", "small", "floppy", true),
  b("weimaraner", "Weimaraner", "ויימרנר", "sporting", "large", "floppy"),
  b("rough_collie", "Collie", "קולי", "herding", "large", "folded"),
  b(
    "newfoundland",
    "Newfoundland",
    "ניופאונדלנד",
    "working",
    "large",
    "floppy",
  ),
  b(
    "rhodesian_ridgeback",
    "Rhodesian Ridgeback",
    "רודזיאן רידג'בק",
    "hound",
    "large",
    "floppy",
  ),
  b("shiba_inu", "Shiba Inu", "שיבה אינו", "spitz", "medium", "pointed", true),
  b(
    "west_highland_white_terrier",
    "West Highland White Terrier",
    "ווסטי",
    "terrier",
    "small",
    "pointed",
  ),
  b(
    "bichon_frise",
    "Bichon Frise",
    "בישון פריזה",
    "non_sporting",
    "small",
    "floppy",
  ),
  b("akita", "Akita", "אקיטה", "spitz", "large", "pointed"),
  b("samoyed", "Samoyed", "סמוייד", "spitz", "large", "pointed"),
  b("bloodhound", "Bloodhound", "בלאדהאונד", "hound", "large", "floppy"),
  b("basset_hound", "Basset Hound", "באסט האונד", "hound", "medium", "floppy"),
  b("whippet", "Whippet", "וויפט", "hound", "medium", "folded"),
  b("greyhound", "Greyhound", "גרייהאונד", "hound", "large", "folded"),
  b(
    "italian_greyhound",
    "Italian Greyhound",
    "גרייהאונד איטלקי",
    "toy",
    "small",
    "folded",
  ),
  b(
    "jack_russell_terrier",
    "Jack Russell Terrier",
    "ג'ק ראסל טרייר",
    "terrier",
    "small",
    "folded",
    true,
  ),
  b(
    "staffordshire_bull_terrier",
    "Staffordshire Bull Terrier",
    "סטאפורדשייר בול טרייר",
    "terrier",
    "medium",
    "folded",
  ),
  b(
    "american_staffordshire_terrier",
    "American Staffordshire Terrier",
    "אמסטף",
    "terrier",
    "medium",
    "folded",
    true,
  ),
  b(
    "american_pit_bull_terrier",
    "American Pit Bull Terrier",
    "פיטבול",
    "terrier",
    "medium",
    "folded",
    true,
  ),
  b(
    "bull_terrier",
    "Bull Terrier",
    "בול טרייר",
    "terrier",
    "medium",
    "pointed",
  ),
  b(
    "cairn_terrier",
    "Cairn Terrier",
    "קרן טרייר",
    "terrier",
    "small",
    "pointed",
  ),
  b(
    "scottish_terrier",
    "Scottish Terrier",
    "סקוטיש טרייר",
    "terrier",
    "small",
    "pointed",
  ),
  b(
    "airedale_terrier",
    "Airedale Terrier",
    "איירדייל טרייר",
    "terrier",
    "large",
    "folded",
  ),
  b("papillon", "Papillon", "פפיון", "toy", "small", "pointed"),
  b(
    "chinese_crested",
    "Chinese Crested",
    "קרסטד סיני",
    "toy",
    "small",
    "pointed",
  ),
  b("lhasa_apso", "Lhasa Apso", "להסה אפסו", "non_sporting", "small", "floppy"),
  b("dalmatian", "Dalmatian", "דלמטי", "non_sporting", "large", "floppy"),
  b("chow_chow", "Chow Chow", "צ'או צ'או", "non_sporting", "medium", "pointed"),
  b("shar_pei", "Shar Pei", "שאר פיי", "non_sporting", "medium", "folded"),
  b(
    "alaskan_malamute",
    "Alaskan Malamute",
    "מלמוט אלסקי",
    "spitz",
    "large",
    "pointed",
  ),
  b("saint_bernard", "Saint Bernard", "סן ברנרד", "working", "large", "floppy"),
  b("bullmastiff", "Bullmastiff", "בולמסטיף", "working", "large", "floppy"),
  b(
    "great_pyrenees",
    "Great Pyrenees",
    "פירנאים",
    "working",
    "large",
    "floppy",
  ),
  b("leonberger", "Leonberger", "לאונברגר", "working", "large", "floppy"),
  b(
    "australian_cattle_dog",
    "Australian Cattle Dog",
    "כלב בקר אוסטרלי",
    "herding",
    "medium",
    "pointed",
  ),
  b(
    "old_english_sheepdog",
    "Old English Sheepdog",
    "רועה אנגלי עתיק",
    "herding",
    "large",
    "floppy",
  ),
  b(
    "bearded_collie",
    "Bearded Collie",
    "קולי מזוקן",
    "herding",
    "medium",
    "floppy",
  ),
  b(
    "anatolian_shepherd",
    "Anatolian Shepherd",
    "רועה אנטולי",
    "working",
    "large",
    "floppy",
  ),
  b(
    "portuguese_water_dog",
    "Portuguese Water Dog",
    "כלב מים פורטוגזי",
    "sporting",
    "medium",
    "floppy",
  ),
  b("irish_setter", "Irish Setter", "סטר אירי", "sporting", "large", "floppy"),
  b(
    "flat_coated_retriever",
    "Flat-Coated Retriever",
    "רטריבר שטוח פרווה",
    "sporting",
    "large",
    "floppy",
  ),
  b(
    "chesapeake_bay_retriever",
    "Chesapeake Bay Retriever",
    "רטריבר צ'סאפיק ביי",
    "sporting",
    "large",
    "floppy",
  ),
  b(
    "nova_scotia_duck_tolling_retriever",
    "Nova Scotia Duck Tolling Retriever",
    "טולר",
    "sporting",
    "medium",
    "floppy",
  ),
  b(
    "english_setter",
    "English Setter",
    "סטר אנגלי",
    "sporting",
    "large",
    "floppy",
  ),
  b("pointer", "Pointer", "פוינטר", "sporting", "large", "floppy"),
  b(
    "german_shorthaired_pointer",
    "German Shorthaired Pointer",
    "פוינטר גרמני קצר שיער",
    "sporting",
    "large",
    "floppy",
  ),
  b(
    "miniature_pinscher",
    "Miniature Pinscher",
    "פינצ'ר ננסי",
    "toy",
    "small",
    "pointed",
  ),
  b("pekingese", "Pekingese", "פקינז", "toy", "small", "floppy"),
  b("keeshond", "Keeshond", "קיסהונד", "spitz", "medium", "pointed"),
  b(
    "finnish_lapphund",
    "Finnish Lapphund",
    "לאפהונד פיני",
    "spitz",
    "medium",
    "pointed",
  ),
  b(
    "norwegian_elkhound",
    "Norwegian Elkhound",
    "אלקהאונד נורבגי",
    "spitz",
    "medium",
    "pointed",
  ),
  b("basenji", "Basenji", "בסנג'י", "hound", "small", "pointed"),
  b("afghan_hound", "Afghan Hound", "כלב אפגני", "hound", "large", "floppy"),
  b("saluki", "Saluki", "סלוקי", "hound", "large", "floppy"),
  b("borzoi", "Borzoi", "בורזוי", "hound", "large", "folded"),
  b(
    "irish_wolfhound",
    "Irish Wolfhound",
    "כלב זאבים אירי",
    "hound",
    "large",
    "folded",
  ),
  b(
    "standard_schnauzer",
    "Standard Schnauzer",
    "שנאוצר",
    "working",
    "medium",
    "folded",
  ),
  b(
    "giant_schnauzer",
    "Giant Schnauzer",
    "שנאוצר ענק",
    "working",
    "large",
    "folded",
  ),
  b(
    "coton_de_tulear",
    "Coton de Tulear",
    "קוטון דה טולאר",
    "toy",
    "small",
    "floppy",
  ),
  b(
    "lagotto_romagnolo",
    "Lagotto Romagnolo",
    "לאגוטו רומניולו",
    "sporting",
    "medium",
    "floppy",
  ),
];
